// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxFsMDA6QCmfWNNs0vDxqIrEEB7Mzosys',
    appId: '1:996575906508:web:e132981389769a8aec1069',
    messagingSenderId: '996575906508',
    projectId: 'trial-439b8',
    authDomain: 'trial-439b8.firebaseapp.com',
    storageBucket: 'trial-439b8.appspot.com',
    measurementId: 'G-D6FN3K0N83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr42Ic0JFqGQUlRdKD48JnMFfK2dFHDOc',
    appId: '1:996575906508:android:0bb1b1f9eeb45f72ec1069',
    messagingSenderId: '996575906508',
    projectId: 'trial-439b8',
    storageBucket: 'trial-439b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2vATuG6VxYvCLQacY3cwptbGsYfQcJdU',
    appId: '1:996575906508:ios:b60b86693697e046ec1069',
    messagingSenderId: '996575906508',
    projectId: 'trial-439b8',
    storageBucket: 'trial-439b8.appspot.com',
    iosBundleId: 'com.example.pemmobModul3Demo',
  );
}
