// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6PjudN64p0pAl1jdQ8GBjuwN2DWqDtHs',
    appId: '1:223662331979:web:de3555d6b924177aa995ce',
    messagingSenderId: '223662331979',
    projectId: 'regrist-codelab',
    authDomain: 'regrist-codelab.firebaseapp.com',
    storageBucket: 'regrist-codelab.appspot.com',
    measurementId: 'G-0HS3504QGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqP9jDTCKlyGp_hTw6hIIy8wtyGAuyc8E',
    appId: '1:223662331979:android:45808baa46250235a995ce',
    messagingSenderId: '223662331979',
    projectId: 'regrist-codelab',
    storageBucket: 'regrist-codelab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdUBdTE4nWuum8IOdE4o-qQskNXMlW85s',
    appId: '1:223662331979:ios:3e39076862fa62eea995ce',
    messagingSenderId: '223662331979',
    projectId: 'regrist-codelab',
    storageBucket: 'regrist-codelab.appspot.com',
    iosBundleId: 'com.example.codelabTugas1Modul3',
  );
}
